# Generated by Django 5.2.9 on 2025-12-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_broadcast',
            field=models.BooleanField(default=False, help_text='If true, this task is visible to all drivers until assigned'),
        ),
    ]
