# Generated by Django 5.2.9 on 2026-01-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
